### ISSUE TITLE
崽崽修行路一

### ISSUE THREAD

**Issue by CStianya** [CStianya/ForZaiZai#1]
> 2017年1月21日
### 1. 知识点
- 顺序程序设计
- 选择程序设计
### 2. 任务
- 阅读完PPT第三章和第四章的内容
- 完成这两章各自对应的程序设计题
![8v0em aa p37uq 4dfhqu6](https://cloud.githubusercontent.com/assets/20432947/22175171/b62a627e-e02a-11e6-9042-ded13f7a478e.png)
![v g53q9 fboc c 0 hdqc9](https://cloud.githubusercontent.com/assets/20432947/22175174/c1b9c418-e02a-11e6-9169-53b184bfc095.png)
### 3. 期限
21日晚上9点前

**Comment by CStianya** [comment]
[程序作业题一下载链接](http://pan.baidu.com/s/1eS1JnSu)

**Comment by ZhenZY** [comment]
崽崽最喜欢最喜欢吃甜甜圈了！因为她觉得吃甜甜圈可以拯救世界！！！

**Comment by CStianya** [comment]
`/*小明果树Xmtree */ 

#include <cstdio>
#include <vector>
#include <stack>
using namespace std;

const int MAX_N = 100005;

vector<int> node[MAX_N];
int par[MAX_N];
/*
void makeTree(int v) {
	int sz = node[v].size();
	for (int i = 0; i < sz; ++i) {
		if (!par[node[v][i]]) {
			par[node[v][i]] = v;
			makeTree(node[v][i]);
		}
	}
}
*/

/*父子结点关系确定*/ 
/*用栈保存时实现深度有限搜索，用队列保存时实现广度有限搜索*/ 
void makeTree() {
	vector<int> node[MAX_N];
	stack<int> s;
	par[1] = 1;
	s.push(1);
	while (s.size()) {
		int v = s.top();
		s.pop();
		int sz = node[v].size();
		for (int i = 0; i < sz; ++i) {
			if (!par[node[v][i]]) {
				par[node[v][i]] = v;
				s.push(node[v][i]);
			}
		}
	}
}

int main () {
	int n, m, a, b, v, edge = 0;
	scanf("%d %d", &n, &m);
	for (int i = 1; i < n; ++i) {
		scanf("%d %d", &a, &b);
		node[a].push_back(b);
		node[b].push_back(a);
	}
	makeTree();
	par[1] = 0; // par[v]=0 ￡onode V visited. 
	while (m--) {
		scanf("%d", &v);
		while (par[v]) {
			int parent = par[v];
			par[v] = 0;
			v = parent;
			++edge;
		}
	}
	printf("%d\n", 2 * edge);
	return 0;
}
 
 
 /*错误代码   
   掌握其中用数组表示的父子结点关系（其中儿子结点的下标大于父亲结点的下标）
 */
 
 /******
 
            #include<cstdio>  
int n,m,i,j,f[100005],u[100005],x,y,t,ans;;  
int main(){  
    scanf("%d%d",&n,&m);  
    for(ans=i=0; i<=n; ++i) f[i]=u[i]=0;  
    for(i=1; i<n; x<y?f[y]=x:f[x]=y,++i) scanf("%d%d",&x,&y);  
    for(u[1]=i=1; i<=m; ++i){  
        scanf("%d",&t);  
        for(j=t; !u[j]; j=f[j]) ans+=2,u[j]=1;  
    }  
    printf("%d\n",ans);  
}  
 ****/   `
